# Generated by Django 5.0.4 on 2024-04-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
