# Generated by Django 5.0.4 on 2024-04-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='moves',
            field=models.TextField(default=''),
        ),
    ]
