# Generated by Django 5.0.4 on 2024-04-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_task_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pgn',
            field=models.TextField(default=''),
        ),
    ]
