# Generated by Django 5.0.4 on 2024-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_task_pgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='side',
            field=models.CharField(max_length=5),
        ),
    ]
